openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API to demonstrate OpenAPI specifications.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server
paths:
  /auth/google:
    get:
      summary: Authenticate with Google OAuth
      description: Returns a URL to authenticate with Google OAuth.
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Invalid credentials

        "403":
          description: Access denied

  /auth/google/callback:
    get:
      summary: Get a JWT token from Google OAuth
      description: Returns a JWT token from Google OAuth.
      responses:
        "200":
          description: A JWT token and User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token
                  user:
                    $ref: "#/components/schemas/User"

        "500":
          description: Authentication failed
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The user ID
        name:
          type: string
          description: The user's name
        email:
          type: string
          description: The user's email
        picture:
          type: string
          description: The user's profile picture
        googleId:
          type: string
          description: The user's Google ID
        college:
          type: string
          description: The user's college
        program:
          type: string
          description: The user's program
        sections:
          type: array
          items:
            $ref: "#/components/schemas/SectionUser"
          description: The user's sections
        gpa:
          type: number
          description: The user's GPA
    SectionUser:
      type: object
      properties:
        sectionId:
          type: string
          description: The section ID
        semester:
          type: number
          description: The semester
        year:
          type: number
          description: The year
        grade:
          type: number
          description: The grade
        isFinished:
          type: boolean
          description: Whether the section is finished
