openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API to demonstrate OpenAPI specifications.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server
paths:
  /users:
    get:
      summary: List all users
      description: Returns a list of users.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /users/{userId}:
    get:
      summary: Get a user by ID
      description: Returns a single user.
      parameters:
        - in: path
          name: userId
          required: true
          description: ID of the user to return
          schema:
            type: string
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The user ID
        name:
          type: string
          description: The user's name
        email:
          type: string
          description: The user's email
