version: "3.8"
services:
  app:
    container_name: college-hack-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - app-network
    volumes:
      - ./dist:/app/dist
networks:
  app-network: